import { Inter } from "next/font/google";
import "./globals.css";
import MaterialProvider from "@/providers/MaterialProvider";
import NavListMenu from "@/components/layouts/header/header";
import { SimpleFooter } from "@/components/layouts/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <MaterialProvider>
        <body className={inter.className+ "relative"}>
          <NavListMenu />
          {children}
          <SimpleFooter />
          </body>
      </MaterialProvider>
    </html>
  );
}
