import { Inter } from "next/font/google";
import "./globals.css";
import MaterialProvider from "@/providers/MaterialProvider";
import NavListMenu from "@/components/layouts/header/header";
import { SimpleFooter } from "@/components/layouts/footer/footer";
import { ClerkProvider } from "@clerk/nextjs";
import "sweetalert2/src/sweetalert2.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <MaterialProvider>
        <ClerkProvider>
          <body className={inter.className + "relative"}>
            <NavListMenu />
            <div className="min-h-screen max-w-screen-xl mx-auto">
              {children}
            </div>
            <SimpleFooter />
          </body>
        </ClerkProvider>
      </MaterialProvider>
    </html>
  );
}
